FROM node:18 as build

# Set environment variables for React
ARG REACT_APP_BASE_URL
ARG REACT_APP_ENDPOINT
ARG REACT_APP_ENVIRONMENT
ARG REACT_APP_GOOGLE_APIKEY
ARG REACT_APP_GOOGLE_CLIENTID
ARG REACT_APP_MICROSOFT_APPID
ARG REACT_APP_MICROSOFT_AUTHORITY
ARG REACT_APP_RECAPTCHA_SITE_KEY
ARG REACT_APP_SENTRY_CONNECTION_STRING
ARG REACT_APP_SOCKET_BASE_URL

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn install --force

COPY . .

RUN yarn build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
