[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install typescript --legacy-peer-deps && NODE_OPTIONS='--max_old_space_size=4096' npm run build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18"
  NODE_ENV = "development"

[build.processing]
  skip_processing = true  

  [context.production.environment]
  NODE_ENV = "development"