[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
command = "npm install typescript --legacy-peer-deps && npm run build"
publish = "build"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18"
  NODE_ENV = "development"
   CI = "false"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_BASE_URL,REACT_APP_MICROSOFT_AUTHORITY,REACT_APP_MICROSOFT_APPID,REACT_APP_GOOGLE_APIKEY,REACT_APP_SOCKET_BASE_URL,REACT_APP_GOOGLE_CLIENTID,REACT_APP_RECAPTCHA_SITE_KEY"


[build.processing]
  skip_processing = true  

  [context.production.environment]
  NODE_ENV = "development"