 require('cypress-xpath');
describe("Analytics", ()=> {
    beforeEach( () => {
        cy.visit("https://devv.plugonline.io/")
    })
    it("Analytics verifications", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("//span[contains(text(),'Analytics')]").should("be.visible").click()
       // .xpath("//div[contains(text(),'Track initiated workflow instances')]").should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(1) > span:nth-child(1) > div:nth-child(1) > div:nth-child(2) > p:nth-child(1)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(2) > p:nth-child(1)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(3) > p:nth-child(1)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(4) > p:nth-child(1)")
        .should("be.visible")
        .get('body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(5) > p:nth-child(1)')
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(6) > span:nth-child(1) > div:nth-child(1) > p:nth-child(1)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1) > div:nth-child(7) > p:nth-child(1)")
        .should("be.visible")
        .xpath("//p[normalize-space()='Actions']").should("be.visible")
        

    })

    it("Analytics reminder", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("//span[contains(text(),'Analytics')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1)")
        .should("be.visible")
        .xpath("//div[@id='analytics-single-workflow-0']//li[@class='MuiListItem-root jss3827 MuiListItem-gutters']")
        .should("not.be.empty")
        .get("#analytics-single-workflow-0 > li > div:nth-child(8) > span > div > div > p > a").click()
        //.xpath('//*[@id="root"]/div/div/div[2]/div/div[2]/div[2]/div[1]/p').contains("Task History")
        cy.get("#app-analytics-data-task-status-0 > button > span.MuiIconButton-label > svg").click()
        .xpath("//li[normalize-space()='Send Reminder']").should("be.visible")
        .click()
        cy.get('.Toastify__toast-body').should("exist")
        .contains("Task reminder mail has been sent")

    }) 

    it("Analytics Reassign task", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("//span[contains(text(),'Analytics')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1)")
        .should("be.visible")
        .xpath("//div[@id='analytics-single-workflow-0']//li[@class='MuiListItem-root jss3827 MuiListItem-gutters']")
        .should("not.be.empty")
        .get("#analytics-single-workflow-0 > li > div:nth-child(8) > span > div > div > p > a").click()
        //.xpath('//*[@id="root"]/div/div/div[2]/div/div[2]/div[2]/div[1]/p').contains("Task History")
        cy.get("#app-analytics-data-task-status-0 > button > span.MuiIconButton-label > svg").click()
        .xpath("//li[normalize-space()='Reassign Task']").should("be.visible")
        .click()
        .xpath("//div[@title='selectDropDown']").click()
        cy.get("div[title='selectDropDown']").should('be.visible').click()
        .type("Test Account")
        .get("[id=select-on-steroid-result-ut-id-1]").click()
        .get("#defaultRTE_rte-edit-view").type("hello world")
        .get(".email-body-save-btn").click()
        .get(".MuiButton-label").click()
        .get("div[role='alert']").contains("Task was reassigned successfully.")


    }) 
    it("Analytics Reassign task without assignee", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("//span[contains(text(),'Analytics')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)")
        .should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > ul:nth-child(1) > li:nth-child(1) > ul:nth-child(1) > div:nth-child(2) > li:nth-child(1)")
        .should("be.visible")
        .xpath("//div[@id='analytics-single-workflow-0']//li[@class='MuiListItem-root jss3827 MuiListItem-gutters']")
        .should("not.be.empty")
        .get("#analytics-single-workflow-0 > li > div:nth-child(8) > span > div > div > p > a").click()
        cy.get("#app-analytics-data-task-status-0 > button > span.MuiIconButton-label > svg").click()
        .xpath("//li[normalize-space()='Reassign Task']").should("be.visible")
        .click()
        .get("#defaultRTE_rte-edit-view").type("hello world")
        .get(".email-body-save-btn").click()
        .get(".MuiButton-label").click()
        .get("div[role='alert']").contains("Please select an assignee to submit")


    }) 
   

    
})