require('cypress-xpath');
describe("App Categories", () => {
    beforeEach( () => {
        cy.visit("https://devv.plugonline.io/")
    })

    it("Create categogries", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("#root > div > div.MuiBox-root.css-0 > div.MuiDrawer-root.MuiDrawer-docked.main-nav-drawer._open.css-1w12bo > div > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span > li > div > div.MuiListItemText-root.side-nav-text.css-1nmt8ps > span")
        .click()
        //.get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(15) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(6) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .xpath("//span[contains(text(),'App Categories')]")
        .click()
        .get("div[title='Add new category']").should("be.visible").click()
        .xpath("//h2[normalize-space()='add App Category']").should("be.visible")
        .xpath("//input[@id='outlined-basic']")
        .type("Cypress Category 1o")
        .get("#save-category-btn").click()
        .xpath("//p[normalize-space()='Cypress Category']").should("be.visible")
        
    })
    
    it("Create categogries duplicate", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("#root > div > div.MuiBox-root.css-0 > div.MuiDrawer-root.MuiDrawer-docked.main-nav-drawer._open.css-1w12bo > div > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span > li > div > div.MuiListItemText-root.side-nav-text.css-1nmt8ps > span")
        .click()
        //.get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(15) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(6) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .xpath("//span[contains(text(),'App Categories')]")
        .click()
        .get("div[title='Add new category']").should("be.visible").click()
        .xpath("//h2[normalize-space()='add App Category']").should("be.visible")
        .xpath("//input[@id='outlined-basic']")
        .type("Cypress Category")
        .get("#save-category-btn").click()
        //.xpath("//p[normalize-space()='Cypress Category']").should("be.visible")
        .xpath("//div[@role='alert']").should("be.visible")
        .contains("Duplicate record is not allowed")
    })

    it("Create categogries without name", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("#root > div > div.MuiBox-root.css-0 > div.MuiDrawer-root.MuiDrawer-docked.main-nav-drawer._open.css-1w12bo > div > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span > li > div > div.MuiListItemText-root.side-nav-text.css-1nmt8ps > span")
        .click()
        //.get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(15) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(6) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .xpath("//span[contains(text(),'App Categories')]")
        .click()
        .get("div[title='Add new category']").should("be.visible").click()
        .xpath("//h2[normalize-space()='add App Category']").should("be.visible")
        .xpath("//input[@id='outlined-basic']")
        //.type("Cypress Category")
        //.get("#save-category-btn").click()
        //.xpath("//p[normalize-space()='Cypress Category']").should("be.visible")
        //.xpath("//div[@role='alert']").should("be.visible")
        //.contains("Duplicate record is not allowed")
    })
})