require('cypress-xpath');

describe("Datasheet", () =>{
    beforeEach( () => {
        cy.visit("https://devv.plugonline.io/")
    })
    
    it("Datasheet creation", () => {
        // Generate random name 
      const randomName = `User${Math.floor(Math.random() * 1000)}`;
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        cy.get('[data-testid="createButton"]').should("be.visible").click()
        .get("h2[class='MuiTypography-root MuiTypography-h6']").should("be.visible")
        .get("input[placeholder='Enter DataSheet name']").should("be.empty")
        .type(randomName)
        .xpath("(//span[normalize-space()='Create'])[1]").should("be.visible").click()
        //.xpath("//div[normalize-space()='Cypress Datasheet 2']").should("be.visible")

    })
    
    it("Datasheet creation duplicate", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        cy.get('[data-testid="createButton"]').should("be.visible").click()
        .get("h2[class='MuiTypography-root MuiTypography-h6']").should("be.visible")
        .get("input[placeholder='Enter DataSheet name']").should("be.empty")
        .type('CypDatasheet1')
        .xpath("(//span[normalize-space()='Create'])[1]").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Duplicate record is not allowed")
    })


    it("Datasheet creation without name", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        cy.get('[data-testid="createButton"]').should("be.visible").click()
        .get("h2[class='MuiTypography-root MuiTypography-h6']").should("be.visible")
        .get("input[placeholder='Enter DataSheet name']").should("be.empty")
        //.type('Cypress Datasheet 2')
       //.xpath("(//span[normalize-space()='Create'])[1]").should("not.be.visible")
        //.xpath("//div[normalize-space()='Cypress Datasheet 2']").should("be.visible")

    })

    
    it("column creation with repeated values", () => {
        // Generate random name 
        const randomName = `User${Math.floor(Math.random() * 1000)}`;
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type(randomName)
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath('//*[@id="root"]/div[2]/div[2]/p[5]').should("be.visible")
        //cy.get('.jss5010 > :nth-child(9)').should("be.visible")
        //.get("#root > div.jss1338 > div.jss1341 > p:nth-child(9)").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Column added")
        //.xpath("//div[contains(text(),'Cypress Colun 21')]").should("be.visible")
        
    })  
    
    it("column creation duplicate", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type("Cypress Column 21")
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath('//*[@id="root"]/div[2]/div[2]/p[5]').should("be.visible")
        //cy.get('.jss5010 > :nth-child(9)').should("be.visible")
        //.get("#root > div.jss1338 > div.jss1341 > p:nth-child(9)").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Unable to create column with an existing name")
        //.xpath("//div[contains(text(),'Cypress Column 12')]").should("be.visible")
        
    })  

    it("column creation with repeated values", () => {
        // Generate random name 
        const randomName = `User${Math.floor(Math.random() * 1000)}`;
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type(randomName)
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath('//*[@id="root"]/div[2]/div[2]/p[5]').should("be.visible")
        //cy.get('.jss5010 > :nth-child(9)').should("be.visible")
        //.get("#root > div.jss1338 > div.jss1341 > p:nth-child(9)").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Column added")
        //.xpath("//div[contains(text(),'Cypress Colun 21')]").should("be.visible")
        
    })  
    
    it("column creation with unique values", () => {
        // Generate random name 
        const randomName = `User${Math.floor(Math.random() * 1000)}`;
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type(randomName)
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible")
        .xpath("//li[normalize-space()='Unique values']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Column added")
        
        
    }) 

    it.only("column creation duplicate", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type("Cypress Column 21")
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .get("div[role='alert']").should("be.visible")
        .contains("Unable to create column with an existing name")
        //.xpath("//div[contains(text(),'Cypress Column 12')]").should("be.visible")
        
    })  
    
    it("column creation without name", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        //.type("Cypress Column 1")
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath("//p[normalize-space()='Default value (Optional)']").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        //.xpath("//div[contains(text(),'Cypress Column 1')]").should("be.visible")
        .get("div[role='alert']").should("be.visible")
        .contains("div[role='alert']", "Please fill up the necessary field(s)")
    })

    it("column creation without name", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        //.type("Cypress Column 1")
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Text']").should("be.visible")
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath("//p[normalize-space()='Default value (Optional)']").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        //.xpath("//div[contains(text(),'Cypress Column 1')]").should("be.visible")
        .get("div[role='alert']").should("be.visible")
        .contains("div[role='alert']", "Please fill up the necessary field(s)")
    })


    
    it("row creation", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        cy.get('[style="font-size: 18px; font-weight: 600; color: rgb(83, 83, 83); white-space: nowrap;"]').should("be.visible")
        .xpath("(//span[@class='MuiTypography-root MuiTypography-body1 MuiListItemText-primary css-yb0lig'][normalize-space()='Apps'])[1]")
        .should("be.visible")
        .xpath("//span[contains(text(),'Datasheets')]").should("be.visible").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2)").should("be.visible")
        .get("div:nth-child(6) div:nth-child(3) button:nth-child(1)").should("be.visible").click()
        cy.get('[data-testid="createButton"] > .MuiSvgIcon-root').should("be.visible").click()
        .xpath("//li[normalize-space()='Add column']").should("be.visible").click()
        .get("#form-dialog-title").should("be.visible")
        .get("input[placeholder='Enter name here'][name='name']").should('be.empty')
        .type("Cypress Column 2a")
        //cy.contains('[inputmode="text"] > .MuiInputBase-root > .MuiInputBase-input', "Cypress Column 1")
        .get("#mui-component-select-dataType").should("be.visible").click()
        .xpath("//li[normalize-space()='Email']").should("be.visible")
        .xpath("//li[normalize-space()='Number']").should("be.visible")
        .xpath("//li[normalize-space()='Date']").should("be.visible")
        .xpath("//li[normalize-space()='Boolean']").should("be.visible")
        .xpath("//li[normalize-space()='Text']").should("be.visible").click()
        .get("#mui-component-select-isUnique").should("be.visible").click()
        .xpath("//li[normalize-space()='Unique values']").should("be.visible")
        .xpath("//li[normalize-space()='Values can be repeated']").should("be.visible").click()
        .get("#mui-component-select-hasNull").should("be.visible").click()
        .xpath("//li[normalize-space()='No, it must be filled']").should("be.visible")
        .xpath("//li[normalize-space()='Yes, it can be null']").should("be.visible").click()
        //.xpath("//p[normalize-space()='Default value (Optional)']").should("be.visible")
        .get("input[placeholder='Enter default value for this column']").should("be.empty")
        .get("#mui-component-select-order").should("be.visible").click()
        .xpath("//li[normalize-space()='At the end']").should("be.visible").click()
        .get("button[title='addColumnBtn'] span[class='MuiButton-label']").should("be.visible").click()
        .xpath("//button[@title='closeBtn']//span[@class='MuiIconButton-label']//*[name()='svg']").should("be.visible").click()
        .xpath("//div[@title='Add new row/column']//*[name()='svg']").click()
        .xpath("//li[normalize-space()='Add data row']").click()
        .get("h2[class='MuiTypography-root MuiTypography-h6']").should("be.visible")
        //.get("input[placeholder='Enter qwertyu345 here']").should("be.visible")
        .get("body > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > input:nth-child(1)")
        .should("be.visible")
        .type("true")
        .get("button[title='addRowBtn'] span[class='MuiButton-label']")
        .should("be.visible").click()
       

    })
})