require('cypress-xpath');
describe('Settings', () => {
    beforeEach( () => {
        cy.visit("https://devv.plugonline.io/")
    })

    const name= "John"

    it("Account Profile", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .should("be.visible").click() 
        .xpath("//span[contains(text(),'Account Profile')]").click()
        .get("input[placeholder='Enter your first name']").should("be.visible")
        //.get("name","John")
        .type('{selectall}{backspace}')
        .should('have.value', '')
        .type("Johnny")
        .get("input[placeholder='Enter your last name']").should("be.visible")
        .type('{selectall}{backspace}')
        .should('have.value', '')
        .type("Wicky")
        //verify phone number not complete because of otp
        //.xpath("//span[normalize-space()='Click here to verify']").should("be.visible")
       //.click()
        .get("#profile-settings-user-role").should("be.visible")//.click()
        .get("#profile-settings-organisation-name").should("be.visible")
        .clear()
        .should('have.value', '')
        .type("Fiber Optizc")
        .get("#profile-settings-organisation-email").should("be.visible")
        .type('{selectall}{del}')
        .should('have.value', '')
        .type("fiberptiz@malinator.com")
        .xpath("//div[@id='profile-settings-organisation-noe']").click()
        .xpath("//li[normalize-space()='1 - 25']").should("be.visible")
        .xpath("//li[normalize-space()='26 - 50']").should("be.visible")
        .xpath("//li[normalize-space()='51 - 100']").should("be.visible")
        .xpath("//li[normalize-space()='101 - 500']").should("be.visible")
        .xpath("//li[normalize-space()='> 500']").should("be.visible")
        .click()
        .xpath("//div[@id='profile-settings-organisation-country']").click()
        .xpath("//li[normalize-space()='Others']").should("be.visible")
        .xpath("//li[normalize-space()='Ghana']").should("be.visible")
        .xpath("//li[normalize-space()='Nigeria']").should("be.visible").click()
        .xpath("//div[@id='profile-settings-organisation-industry']").click()
        .xpath("//li[normalize-space()='Others']").should("be.visible")
        .xpath("//li[normalize-space()='NGO']").should("be.visible")
        .xpath("//li[normalize-space()='Management Consulting']").should("be.visible")
        .xpath("//li[normalize-space()='Insurance']").should("be.visible")
        .xpath("//li[normalize-space()='Information Technology']").should("be.visible")
        .xpath("//li[normalize-space()='Hospitality']").should("be.visible")
        .xpath("//li[normalize-space()='Government']").should("be.visible")
        .xpath("//li[normalize-space()='FMCG']").should("be.visible")
        .xpath("//li[normalize-space()='Agriculture']").should("be.visible").click()
        .get("#profile-settings-save-btn").click()
        .get("div[role='alert']").should("be.visible")
        //.contains("Updated Sucessfully")



        //.xpath("//li[normalize-space()='Admin']").should("be.visible")
        //.get("div[id='menu-roles'] li:nth-child(1)").should("be.visible")
        //.xpath("//li[normalize-space()='Employee']").should("be.visible").click()
        //.get('#root > div > div > div.main-page-layout-outer > div > div:nth-child(2) > div > form > div:nth-child(13) > div > input')
        //.should("be.visible")

    })


    it("Password change", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .should("be.visible").click() 
        .xpath("//span[contains(text(),'Password Change')]").click()
        .get("input[placeholder='Enter password here']").should("be.visible")
        .type("Testing123@")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1)")
        .click()    
        .xpath("//input[@placeholder='Enter new password here']").should("be.visible")
        .type("Testing123@") 
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1) > img:nth-child(1)")
        .click()
        cy.get('.MuiFormControl-root > .MuiButtonBase-root').should("be.visible")
        .click()
        
    })
    
    // Introduce a delay of 3 seconds between Test 1 and Test 2
    //it('Delay between tests', () => {
    //cy.delay(3000); // Delays execution for 3000 milliseconds (3 seconds)
    //});
    

    it("Password change without inputting old passward", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        //.type("Testing123#")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .should("be.visible").click() 
        .xpath("//span[contains(text(),'Password Change')]").click()
        .get("input[placeholder='Enter password here']").should("be.visible")
        //.type("Testing123@")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1)")
        .click()    
        .xpath("//input[@placeholder='Enter new password here']").should("be.visible")
        .type("Testing123#")
        //.get("body > div:nths-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1) > img:nth-child(1)")
       // .click()
        //.get(".MuiButtonBase-root.MuiButton-root.jss117.MuiButton-contained.MuiButton-containedPrimary")
        //.should("be.visible").click()
        //xpath("(//button[@class='MuiButtonBase-root MuiButton-root jss117 MuiButton-contained MuiButton-containedPrismary'])[1]").should("be.visible")
        cy.get('.MuiFormControl-root > .MuiButtonBase-root').should("be.visible")
        .should("be.disabled")
        //.xpath("(//p[@class='MuiTypography-root jss338 MuiTypography-body1'])[1]").should("be.visible")
        // no error message shows when  a user tries to change password without inputting the old password and the change button is clickable/active
    })

    it("Password change without inputting new passward", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .should("be.visible").click() 
        .xpath("//span[contains(text(),'Password Change')]").click()
        .get("input[placeholder='Enter password here']").should("be.visible")
        .type("Testing123@")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1)")
        .click()    
        .xpath("//input[@placeholder='Enter new password here']").should("be.visible")
        //.type("Testing123#")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1) > img:nth-child(1)")
        .click()
        cy.get('.MuiFormControl-root > .MuiButtonBase-root')
        .should("be.disabled")
        
    })

    it("Password change without inputting new passward", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("plugtest@mailinator.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Testing123@")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > a:nth-child(14) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .should("be.visible").click() 
        .xpath("//span[contains(text(),'Password Change')]").click()
        .get("input[placeholder='Enter password here']").should("be.visible")
        //.type("Testing123@")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1)")
        .click()    
        .xpath("//input[@placeholder='Enter new password here']").should("be.visible")
        //.type("Testing123#")
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > i:nth-child(1) > img:nth-child(1)")
        .click()
        cy.get('.MuiFormControl-root > .MuiButtonBase-root').should("be.visible")
        
    })

})