require('cypress-xpath');
describe("Template", ()=> {
    beforeEach( () => {
        cy.visit("https://devv.plugonline.io/")
    })

    it("Template creation", () => {
        //cy.get(".MuiTypography-root.jss856.MuiTypography-body1").should("be.visible")
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        //.xpath('"Templates"').should("be.visible")
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        .type("Cypress Template 1")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        .type("Cypress Template Description")
        .get("#mui-component-select-category").click()
        .xpath("//option[normalize-space()='General']").should("be.visible")
        .click()
        .get("#mui-component-select-isPublic").click()
        .xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        .xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        .click()
        .get("button[title='submitBtn']").click()
        //.xpath('//*[@id="root"]/div/div/header/div[1]/div/div[1]').should("be.visible")
        //could not verify that the new template was created as the element name has that jss567, that changes frequently

    })

    it("Template creation Duplicate", () => {
        //cy.get(".MuiTypography-root.jss856.MuiTypography-body1").should("be.visible")
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        //.xpath('"Templates"').should("be.visible")
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        .type("Cypress Template")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        .type("Cypress Template Description")
        .get("#mui-component-select-category").click()
        .xpath("//option[normalize-space()='General']").should("be.visible")
        .click()
        .get("#mui-component-select-isPublic").click()
        .xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        .xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        .click()
        .get("button[title='submitBtn']").click()
        //.xpath('//*[@id="root"]/div/div/header/div[1]/div/div[1]').should("be.visible")
        //could not verify that the new template was created as the element name has that jss567, that changes frequently
        .xpath("//div[@role='alert']"). contains("Duplicate record is not allowed")
 
    })
    it("Template creation without name", () => {
        //cy.get(".MuiTypography-root.jss856.MuiTypography-body1").should("be.visible")
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        //.xpath('"Templates"').should("be.visible")
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        //.type("Cypress Template")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        .type("Cypress Template Description")
        .get("#mui-component-select-category").click()
        .xpath("//option[normalize-space()='General']").should("be.visible")
        .click()
        .get("#mui-component-select-isPublic").click()
        .xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        .xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        .click()
        .get(".MuiFormHelperText-root.MuiFormHelperText-contained.Mui-error.Mui-focused.MuiFormHelperText-marginDense")
        .should("be.visible")
       
    })
    it("Template creation without description", () => {
        //cy.get(".MuiTypography-root.jss856.MuiTypography-body1").should("be.visible")
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        .type("Cypress Template")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        //.type("Cypress Template Description")
        .get("#mui-component-select-category").click()
        .xpath("//option[normalize-space()='General']").should("be.visible")
        .click()
        .get("#mui-component-select-isPublic").click()
        .xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        .xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        .click()
        .get(".MuiFormHelperText-root.MuiFormHelperText-contained.Mui-error")
        .should("be.visible")
       
    })

    it("Template creation without category", () => {
        //cy.get(".MuiTypography-root.jss856.MuiTypography-body1").should("be.visible")
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        .type("Cypress Template")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        .type("Cypress Template Description")
        //.get("#mui-component-select-category").click()
        //.xpath("//option[normalize-space()='General']").should("be.visible")
        //.click()
        .get("#mui-component-select-isPublic").click()
        .xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        .xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        .click()
       
    })

    it("Template creation without selecting if the app is customer facing", () => {
        cy.get("input[placeholder='Enter your email address']").should("be.empty")
        .type("abdulganiyy.ajayi@gmail.com")
        .get("input[placeholder='Enter password here']").should("be.empty")
        .type("Password@1")
        .get("img[alt='Visibility']").click()
        .xpath("//span[normalize-space()='Login']").click()
        .get("body > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(2) > ul:nth-child(1) > div:nth-child(3) > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > a:nth-child(2) > span:nth-child(1) > li:nth-child(1) > div:nth-child(1)")
        .click()
        .get("#root > div > div.MuiBox-root.css-0 > div.main-page-layout-outer > div > div:nth-child(1) > div > div:nth-child(1)")
        .should("be.visible")
        .xpath("//div[contains(@title,'Add new template')]//*[name()='svg']").click()
        .xpath('//*[@id="customized-dialog-title"]/p/span').should("be.visible")
        .get("input[placeholder='Enter name here']").should("be.empty")
        .type("Cypress Template")
        .get("textarea[placeholder='Enter description']").should("be.empty")
        .type("Cypress Template Description")
        .get("#mui-component-select-category").click()
        .xpath("//option[normalize-space()='General']").should("be.visible")
        .click()
        //.get("#mui-component-select-isPublic").click()
        //.xpath("//option[normalize-space()='Internal or employee-facing']").should("be.visible")
        //.xpath("//option[normalize-space()='External or customer-facing']").should("be.visible")
        //.click()
       
    })

})